#ATIVIDADE06
num1,num2=input('Digite um numero: '),input('Digite outro numero: ')
num1=float(num1)
num2=float(num2)
print('Adição ',num1+num2)
print('Subtração ',num1-num2)
print('multiplicacao ',num1*num2)
print('divisão ',num1/num2)
print('divisao inteira',num1//num2)
print('Modulo ',num1%num2)
